# An example of a services.yaml file in an extension

doctrine:
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      Contact_Rendez_Vous:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/vendor/celtic34fr/contact-rdv/src/Entity'
        prefix: 'Celtic34fr\ContactRendezVous'
        alias: ContactRendezVous

services:
  Celtic34fr\ContactRendezVous\AdminMenu:
    class: Celtic34fr\ContactRendezVous\AdminMenu
    arguments: [ '@Symfony\Component\Routing\Generator\UrlGeneratorInterface' ]
    tags: [ 'bolt.extension_backend_menu' ]
